name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        include:
          - name: x86_64-linux
            runner: [ self-hosted, nixos ]
          - name: aarch64-darwin
            runner: [ self-hosted, macos ]
    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Attic cache
        env:
          ATTIC_ENDPOINT: ${{ secrets.ATTIC_ENDPOINT }}
          ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
        run: |
          attic login --set-default admin "$ATTIC_ENDPOINT" "$ATTIC_TOKEN"
          attic use "$ATTIC_CACHE"

      - name: Build and cache flake outputs
        env:
          ATTIC_ENDPOINT: ${{ secrets.ATTIC_ENDPOINT }}
          ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}
        run: |
          nix-instantiate -E '(builtins.getFlake "path:${builtins.toString ./.}").packages."${builtins.currentSystem}".ci' --add-root temp-ci-drv --indirect | \
          nix-store --stdin -q --references | \
          nix-store --stdin --realise -v -j auto | \
          nix-store --stdin -qR --include-outputs | \
          tr '\n' ' ' | \
          xargs attic push "$ATTIC_CACHE"
          rm temp-ci-drv
      # - name: Push built outputs to Attic
      #   #if: github.ref == 'refs/heads/master'
      #   env:
      #     ATTIC_ENDPOINT: ${{ secrets.ATTIC_ENDPOINT }}
      #     ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}
      #   run: nix path-info --recursive ./result-ci | attic push --stdin "$ATTIC_CACHE"
